#pragma once

#define FILE_NAME "\\\\.\\BltBSOD"
#define DEVICE_NAME L"\\Device\\BltBSOD"
#define DEVICE_LINK L"\\??\\BltBSOD" 

#define WRITE_REQUEST CTL_CODE(FILE_DEVICE_UNKNOWN, 0x100, METHOD_BUFFERED, FILE_SPECIAL_ACCESS)
#define READ_REQUEST CTL_CODE(FILE_DEVICE_UNKNOWN, 0x110, METHOD_BUFFERED, FILE_SPECIAL_ACCESS)
#define TERMINATE_REQUEST CTL_CODE(FILE_DEVICE_UNKNOWN, 0x120, METHOD_BUFFERED, FILE_SPECIAL_ACCESS)

struct KERNEL_CLIENT_READ {
	ULONG ProcessId;
	ULONGLONG Address;
	PVOID Buff;
	ULONG Size;
};

struct KERNEL_CLIENT_WRITE {
	ULONG ProcessId;
	ULONGLONG Address;
	PVOID Buff;
	ULONG Size;
};

struct KERNEL_CLIENT_TERMINATE {
	ULONG ProcessId;
};
